In [1]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("./vn30_from_2017_to_2025.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62196 entries, 0 to 62195
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   symbol  62196 non-null  object
 1   time    62196 non-null  object
 2   open    62196 non-null  float64
 3   high    62196 non-null  float64
 4   low     62196 non-null  float64
 5   close   62196 non-null  float64
 6   volume  62196 non-null  int64
dtypes: float64(4), int64(1), object(2)
memory usage: 3.3+ MB

In [3]:
df.describe()

               open          high           low         close        volume
count  62196.000000  62196.000000  62196.000000  62196.000000  6.219600e+04
mean      34.436588     34.866781     33.987523     34.432043  5.617045e+06
std       30.027777     30.378579     29.633744     30.032552  9.722623e+06
min        1.360000      1.420000      1.360000      1.390000  0.000000e+00
25%       11.680000     11.850000     11.510000     11.670000  8.721275e+05
50%       23.500000     23.790000     23.200000     23.500000  2.281711e+06
75%       50.130000     50.802500     49.582500     50.142500  6.292023e+06
max      218.500000    220.000000    212.200000    219.100000  2.497607e+08

In [4]:
df.symbol.nunique()

30

In [6]:
df.groupby('symbol').agg(
    time_min=('time', 'min'),
    time_max=('time', 'max'),
    count=('time', 'size')
)

          time_min    time_max  count
symbol
ACB     2017-01-03  2025-12-31   2244
BID     2017-01-03  2025-12-31   2249
CTG     2017-01-03  2025-12-31   2249
DGC     2017-01-03  2025-12-31   2243
FPT     2017-01-03  2025-12-31   2249
GAS     2017-01-03  2025-12-31   2249
GVR     2018-03-21  2025-12-31   1942
HDB     2018-01-05  2025-12-31   1996
HPG     2017-01-03  2025-12-31   2249
LPB     2017-10-05  2025-12-31   2051
MBB     2017-01-03  2025-12-31   2249
MSN     2017-01-03  2025-12-31   2249
MWG     2017-01-03  2025-12-31   2249
PLX     2017-04-21  2025-12-31   2177
SAB     2017-01-03  2025-12-31   2249
SHB     2017-01-03  2025-12-31   2246
SSB     2021-03-24  2025-12-31   1195
SSI     2017-01-03  2025-12-31   2249
STB     2017-01-03  2025-12-31   2249
TCB     2018-06-04  2025-12-31   1898
TPB     2018-04-19  2025-12-31   1927
VCB     2017-01-03  2025-12-31   2249
VHM     2017-01-03  2025-12-31   2040
VIB     2017-01-09  2025-12-31   2238
VIC     2017-01-03  2025-12-31   2249
VJC     2017-02-28  2025-12-31   2214
VNM     2017-01-03  2025-12-31   2249
VPB     2017-08-17  2025-12-31   2095
VPL     2025-05-13  2025-12-31    165
VRE     2017-11-06  2025-12-31   2039